# analysis groups
samples:

  ancestral_paths_new:
    reference: GRCh37
    metadata: data/Ancestral_paths_new/ancestral_paths_merged_filtered_age.sampleInfo.tsv
    genotypes: data/Ancestral_paths_new/ancestral_paths_merged_filtered.bcf
    is_likelihood: False

  imputed_unfiltered:
    reference: GRCh37
    metadata: data/Ancestral_paths_new/ancestral_paths_merged_filtered_age.sampleInfo.tsv
    genotypes: data/imputed_unfiltered/ancestral_paths_new-all-chrALL-unfiltered-1000G.bcf
    is_likelihood: False

# list of chroms in GRCh37
chroms: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

gen_time: 28

# position of the HLA locus in GRCh37
hla:
  chr: 6
  start: 28477797
  stop: 33448354