channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bcftools=1.15
  - bioconda::pysam=0.18.0
  - bioconda::snakefmt=0.6.0
  - bioconda::snakemake=6.12.3
  - conda-forge::biopython=1.79
  - conda-forge::click=8.0.4
  - conda-forge::matplotlib=3.5.1
  - conda-forge::numba=0.53.1
  - conda-forge::numpy=1.22.2
  - conda-forge::pandas=1.3.4
  - conda-forge::pandas=1.3.4
  - conda-forge::python=3.9.7
  - conda-forge::pyyaml=6.0
  - conda-forge::scipy=1.8.0
