channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bcftools=1.15
  - bioconda::plink=1.90b6.21
  - bioconda::pysam=0.18.0
  - bioconda::snakefmt=0.6.0
  - bioconda::snakemake=6.12.3
  - conda-forge::biopython=1.79
  - conda-forge::click=8.0.4
  - conda-forge::matplotlib=3.5.1
  - conda-forge::numba=0.53.1
  - conda-forge::numpy=1.22.2
  - conda-forge::pandas=1.3.4
  - conda-forge::pandas=1.3.4
  - conda-forge::parallel=20220222
  - conda-forge::progressbar=2.5
  - conda-forge::python=3.9.7
  - conda-forge::pyyaml=6.0
  - conda-forge::r-argparser=0.6
  - conda-forge::r-base=4.0.5
  - conda-forge::r-directlabels=2021.1.13
  - conda-forge::r-ggdist=3.1.1
  - conda-forge::r-jsonlite=1.8.0
  - conda-forge::r-r.utils=2.12.0
  - conda-forge::r-rcppcnpy=0.2.11
  - conda-forge::r-rcpproll=0.3.0
  - conda-forge::r-tidyverse=1.3.1
  - conda-forge::r-zoo=1.8_10
  - conda-forge::scipy=1.8.0
