channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::pysam=0.18.0
  - bioconda::snakemake=6.12.3
  - conda-forge::click=8.0.4
  - conda-forge::pandas=1.3.4
  - conda-forge::pandas=1.3.4
  - conda-forge::python=3.9.7
  - conda-forge::pyyaml=6.0
